version: '3'
services:
  db:
    build:
      context: ./mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - do_rails-mysql-data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    depends_on:
      - nginx
    
  prod:
    build: .
    volumes:
      - .:/do_rails
      - public-data:/do_rails/public
      - tmp-data:/do_rails/tmp
      - log-data:/do_rails/log
    #depends_on:
    #  - db
    stdin_open: true
    tty: true
    #command: bundle exec unicorn -c config/unicorn.rb
    command: bundle exec rails s

  nginx:
    build:
      context: ./nginx
    volumes:
      - public-data:/do_rails/public
      - tmp-data:/do_rails/tmp
    ports:
      - 80:80
    depends_on:
      - prod

volumes:
  #./mysql/initdb.d:
  #./mysql/conf.d:
  do_rails-mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
  db-data:
